{% set name = "hysetter" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hysetter-{{ version }}.tar.gz
  sha256: a64901dbbcc8ba0c10150df0e8b218f43cad04f07d5c572b5df3e2919d06b0c3

build:
  entry_points:
    - hysetter = hysetter.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=60
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.10
    - dask-expr >=1.1
    - flox
    - numba
    - numbagg
    - planetary-computer
    - py3dep >=0.16.3
    - py7zr
    - pydantic
    - pydaymet >=0.16.3
    - pygeohydro >=0.16.3
    - pygeoutils >=0.16.3
    - pygridmet >=0.16
    - pynhd >=0.16.3
    - pynldas2 >=0.16
    - pyogrio
    - pystac-client
    - pyyaml
    - rich-click
    - rioxarray >=0.15.5
    - typing-extensions
    - xarray-spatial

test:
  imports:
    - hysetter
  commands:
    - pip check
    - hysetter --help
  requires:
    - pip

about:
  summary: Subset hydroclimate data using HyRiver over CONUS.
  home: https://github.com/hyriver/hysetter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
